#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
BUNDLE_DIR="$PROJECT_ROOT/app/bundles"
OUT_DIR="$PROJECT_ROOT/dist/bundles"
RELEASE_TAG="${METALSHARP_BUNDLE_TAG:-bundles}"
REPO="${METALSHARP_BUNDLE_REPO:-metalsharp/MetalSharp}"
MANIFEST="$PROJECT_ROOT/tools/bundles/asset-manifest.tsv"
TMP_DIR="$(mktemp -d "${TMPDIR:-/tmp}/metalsharp-create-bundles.XXXXXX")"
REMOTE_MANIFEST="$TMP_DIR/metalsharp-bundle-manifest.tsv"
trap 'rm -rf "$TMP_DIR"' EXIT
REPAIR_BUNDLES="${METALSHARP_REPAIR_BUNDLES:-1}"
SKIP_DEVELOPER_SDK="${METALSHARP_SKIP_DEVELOPER_SDK_BUNDLE:-0}"

mkdir -p "$BUNDLE_DIR" "$OUT_DIR"
curl -fL --retry 3 -o "$REMOTE_MANIFEST" \
  "https://github.com/$REPO/releases/download/$RELEASE_TAG/metalsharp-bundle-manifest.tsv"

release_asset_info() {
  local asset="$1"
  awk -F '\t' -v asset="$asset" \
    '$1 == asset && $3 ~ /^[0-9a-f]{64}$/ && $4 ~ /^[0-9]+$/ { print $3 "\t" $4; exit }' \
    "$REMOTE_MANIFEST"
}

asset_matches_release_manifest() {
  local asset="$1"
  local path="$2"
  local info expected_sha expected_size actual_sha actual_size
  info="$(release_asset_info "$asset")"
  [ -n "$info" ] || return 1
  expected_sha="${info%%$'\t'*}"
  expected_size="${info#*$'\t'}"
  [ -s "$path" ] || return 1
  actual_sha="$(shasum -a 256 "$path" | awk '{print $1}')"
  actual_size="$(wc -c < "$path" | tr -d ' ')"
  [ "$actual_sha" = "$expected_sha" ] && [ "$actual_size" = "$expected_size" ]
}

download_asset() {
  local asset="$1"
  local dest="$2"
  local partial="$dest.part"
  if [ -z "$(release_asset_info "$asset")" ]; then
    echo "Release manifest is missing a valid row for: $asset" >&2
    return 1
  fi
  if [ -s "$dest" ] && asset_matches_release_manifest "$asset" "$dest"; then
    if "$PROJECT_ROOT/tools/bundles/verify-bundles.sh" --bundle-dir "$BUNDLE_DIR" "$asset" >/dev/null 2>&1; then
      echo "SKIP bundle: $asset (matches release manifest)"
      return 0
    fi
  fi
  if [ -e "$dest" ]; then
    echo "Refreshing stale bundle: $asset"
  fi
  echo "Downloading bundle: $asset"
  rm -f "$partial"
  curl -fL --retry 3 -o "$partial" "https://github.com/$REPO/releases/download/$RELEASE_TAG/$asset"
  if ! asset_matches_release_manifest "$asset" "$partial"; then
    echo "Downloaded bundle does not match release manifest: $asset" >&2
    rm -f "$partial"
    return 1
  fi
  mv "$partial" "$dest"
}

repair_assets_fnalibs_bundle() {
  local assets_archive="$BUNDLE_DIR/metalsharp-assets.tar.zst"
  local fnalibs_archive="$BUNDLE_DIR/fnalibs.tar.zst"
  if [ ! -s "$assets_archive" ] || [ ! -s "$fnalibs_archive" ]; then
    return 0
  fi

  local tmp assets_root fnalibs_root
  tmp="$(mktemp -d "${TMPDIR:-/tmp}/metalsharp-assets-fnalibs.XXXXXX")"
  assets_root="$tmp/assets"
  fnalibs_root="$tmp/fnalibs"
  mkdir -p "$assets_root" "$fnalibs_root"

  tar --use-compress-program=unzstd -xf "$assets_archive" -C "$assets_root"
  tar --use-compress-program=unzstd -xf "$fnalibs_archive" -C "$fnalibs_root"

  if [ ! -d "$assets_root/assets" ] || [ ! -d "$fnalibs_root/fnalibs" ]; then
    echo "Unable to repair assets fnalibs payload: unexpected bundle layout" >&2
    rm -rf "$tmp"
    return 1
  fi

  rm -rf "$assets_root/assets/fnalibs"
  rm -rf "$assets_root/assets/eac-toggle"
  mkdir -p "$assets_root/assets"
  cp -R -p "$fnalibs_root/fnalibs" "$assets_root/assets/fnalibs"
  mkdir -p "$assets_root/assets/fna-kickstart/osx"
  for dylib in libFNA3D.0.dylib libSDL2-2.0.0.dylib libFAudio.0.dylib libtheorafile.dylib; do
    cp -p "$fnalibs_root/fnalibs/$dylib" "$assets_root/assets/fna-kickstart/osx/$dylib"
  done

  (
    cd "$assets_root"
    tar -cf "$tmp/metalsharp-assets.tar" assets
  )
  zstd -q -19 -T0 -f "$tmp/metalsharp-assets.tar" -o "$assets_archive"
  chmod 0644 "$assets_archive"
  rm -rf "$tmp"
  echo "repaired assets payload: $assets_archive (fnalibs refreshed, eac-toggle removed)"
}

while IFS=$'\t' read -r asset _root _platforms _notes; do
  case "$asset" in
    ""|\#*) continue ;;
  esac
  if [ "$SKIP_DEVELOPER_SDK" = "1" ] && [ "$asset" = "metalsharp-d3d12-developer-sdk.tar.zst" ]; then
    echo "SKIP bundle: $asset (will be generated by CI)"
    continue
  fi
  download_asset "$asset" "$BUNDLE_DIR/$asset"
done < "$MANIFEST"

if [ "$REPAIR_BUNDLES" = "1" ]; then
  repair_assets_fnalibs_bundle

  REPAIR_ARGS=(
    --archive "$BUNDLE_DIR/metalsharp-runtime.tar.zst"
    --host-dir "$PROJECT_ROOT/app/native/host"
    --backend "$PROJECT_ROOT/app/src-c/build/metalsharp-backend"
  )
  if [ -n "${METALSHARP_X87SIDECAR_PATH:-}" ]; then
    REPAIR_ARGS+=(--x87sidecar "$METALSHARP_X87SIDECAR_PATH")
  fi
  python3 "$PROJECT_ROOT/tools/dmg/repair-runtime-bundle.py" "${REPAIR_ARGS[@]}"
else
  echo "bundle repair disabled; using verified release bundles as downloaded"
fi

VERIFY_ARGS=(--bundle-dir "$BUNDLE_DIR" --require mac)
if [ -n "${METALSHARP_X87SIDECAR_PATH:-}" ]; then
  export METALSHARP_REQUIRE_X87SIDECAR=1
fi
if [ "$SKIP_DEVELOPER_SDK" = "1" ]; then
  while IFS=$'\t' read -r asset _root _platforms _notes; do
    case "$asset" in
      ""|\#*|metalsharp-d3d12-developer-sdk.tar.zst) continue ;;
    esac
    VERIFY_ARGS+=("$asset")
  done < "$MANIFEST"
fi
"$PROJECT_ROOT/tools/bundles/verify-bundles.sh" "${VERIFY_ARGS[@]}"

rm -f "$OUT_DIR"/metalsharp-*.tar.zst
while IFS=$'\t' read -r asset _root _platforms _notes; do
  case "$asset" in
    ""|\#*) continue ;;
  esac
  if [ "$SKIP_DEVELOPER_SDK" = "1" ] && [ "$asset" = "metalsharp-d3d12-developer-sdk.tar.zst" ]; then
    continue
  fi
  cp "$BUNDLE_DIR/$asset" "$OUT_DIR/$asset"
done < "$MANIFEST"

{
  printf 'asset\troot\tsha256\tsize\tnotes\n'
  while IFS=$'\t' read -r asset root _platforms notes; do
    case "$asset" in
      ""|\#*) continue ;;
    esac
    if [ "$SKIP_DEVELOPER_SDK" = "1" ] && [ "$asset" = "metalsharp-d3d12-developer-sdk.tar.zst" ]; then
      continue
    fi
    archive="$BUNDLE_DIR/$asset"
    hash="$(shasum -a 256 "$archive" | awk '{print $1}')"
    size="$(wc -c < "$archive" | tr -d ' ')"
    printf '%s\t%s\t%s\t%s\t%s\n' "$asset" "$root" "$hash" "$size" "$notes"
  done < "$MANIFEST"
} > "$OUT_DIR/metalsharp-bundle-manifest.tsv"

echo ""
echo "=== Split Bundle Summary ==="
ls -lh "$BUNDLE_DIR"/metalsharp-*.tar.zst
