#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
BUNDLE_DIR="$PROJECT_ROOT/app/bundles"
OUT_DIR="$PROJECT_ROOT/dist/bundles"
RELEASE_TAG="${METALSHARP_BUNDLE_TAG:-bundles}"
REPO="${METALSHARP_BUNDLE_REPO:-aaf2tbz/metalsharp}"
MANIFEST="$PROJECT_ROOT/tools/bundles/asset-manifest.tsv"
REPAIR_BUNDLES="${METALSHARP_REPAIR_BUNDLES:-1}"
SKIP_DEVELOPER_SDK="${METALSHARP_SKIP_DEVELOPER_SDK_BUNDLE:-0}"
# M12 (dxmt-m12) dll refresh is off by default. Rebuilding the m12 lane from a
# local runtime root silently changes the dlls and desyncs the bundle from the
# installer's compiled-in DXMT_M12_EXPECTED_HASHES. Set METALSHARP_REPAIR_M12=1
# only when intentionally refreshing the canonical m12 material.
REPAIR_M12="${METALSHARP_REPAIR_M12:-0}"

mkdir -p "$BUNDLE_DIR" "$OUT_DIR"

download_asset() {
  local asset="$1"
  local dest="$2"
  if [ -s "$dest" ]; then
    if "$PROJECT_ROOT/tools/bundles/verify-bundles.sh" --bundle-dir "$BUNDLE_DIR" "$asset" >/dev/null 2>&1; then
      echo "SKIP bundle: $asset"
      return 0
    fi
    echo "Refreshing stale bundle: $asset"
    rm -f "$dest"
  fi
  echo "Downloading bundle: $asset"
  curl -fL --retry 3 -o "$dest" "https://github.com/$REPO/releases/download/$RELEASE_TAG/$asset"
}

repair_graphics_m12_bundle() {
  local archive="$BUNDLE_DIR/metalsharp-graphics-dll.tar.zst"
  local m12_root="${METALSHARP_DXMT_M12_ROOT:-$HOME/.metalsharp/runtime/wine/lib/dxmt_m12}"
  if [ ! -s "$archive" ] || [ ! -d "$m12_root/x86_64-windows" ] || [ ! -d "$m12_root/x86_64-unix" ]; then
    return 0
  fi

  local tmp root
  tmp="$(mktemp -d "${TMPDIR:-/tmp}/metalsharp-graphics-m12.XXXXXX")"
  root="$tmp/root"
  mkdir -p "$root"
  tar --use-compress-program=unzstd -xf "$archive" -C "$root"
  mkdir -p "$root/Graphics/dll/dxmt-m12/x86_64-unix" "$root/Graphics/dll/dxmt-m12/x86_64-windows"
  cp -R -p "$m12_root/x86_64-unix/." "$root/Graphics/dll/dxmt-m12/x86_64-unix/"
  cp -R -p "$m12_root/x86_64-windows/." "$root/Graphics/dll/dxmt-m12/x86_64-windows/"
  (
    cd "$root"
    tar -cf "$tmp/metalsharp-graphics-dll.tar" Graphics
  )
  zstd -q -19 -T0 -f "$tmp/metalsharp-graphics-dll.tar" -o "$archive"
  chmod 0644 "$archive"
  rm -rf "$tmp"
  echo "repaired graphics M12 payload: $archive from $m12_root"
}

repair_assets_fnalibs_bundle() {
  local assets_archive="$BUNDLE_DIR/metalsharp-assets.tar.zst"
  local fnalibs_archive="$BUNDLE_DIR/fnalibs.tar.zst"
  if [ ! -s "$assets_archive" ] || [ ! -s "$fnalibs_archive" ]; then
    return 0
  fi

  local tmp assets_root fnalibs_root
  tmp="$(mktemp -d "${TMPDIR:-/tmp}/metalsharp-assets-fnalibs.XXXXXX")"
  assets_root="$tmp/assets"
  fnalibs_root="$tmp/fnalibs"
  mkdir -p "$assets_root" "$fnalibs_root"

  tar --use-compress-program=unzstd -xf "$assets_archive" -C "$assets_root"
  tar --use-compress-program=unzstd -xf "$fnalibs_archive" -C "$fnalibs_root"

  if [ ! -d "$assets_root/assets" ] || [ ! -d "$fnalibs_root/fnalibs" ]; then
    echo "Unable to repair assets fnalibs payload: unexpected bundle layout" >&2
    rm -rf "$tmp"
    return 1
  fi

  rm -rf "$assets_root/assets/fnalibs"
  rm -rf "$assets_root/assets/eac-toggle"
  mkdir -p "$assets_root/assets"
  cp -R -p "$fnalibs_root/fnalibs" "$assets_root/assets/fnalibs"
  mkdir -p "$assets_root/assets/fna-kickstart/osx"
  for dylib in libFNA3D.0.dylib libSDL2-2.0.0.dylib libFAudio.0.dylib libtheorafile.dylib; do
    cp -p "$fnalibs_root/fnalibs/$dylib" "$assets_root/assets/fna-kickstart/osx/$dylib"
  done

  (
    cd "$assets_root"
    tar -cf "$tmp/metalsharp-assets.tar" assets
  )
  zstd -q -19 -T0 -f "$tmp/metalsharp-assets.tar" -o "$assets_archive"
  chmod 0644 "$assets_archive"
  rm -rf "$tmp"
  echo "repaired assets payload: $assets_archive (fnalibs refreshed, eac-toggle removed)"
}

create_goldberg_bundle() {
  local assets_archive="$BUNDLE_DIR/metalsharp-assets.tar.zst"
  local goldberg_archive="$BUNDLE_DIR/goldberg.tar.zst"
  local tmp assets_root source
  tmp="$(mktemp -d "${TMPDIR:-/tmp}/metalsharp-goldberg-bundle.XXXXXX")"
  assets_root="$tmp/assets"
  mkdir -p "$assets_root"

  tar --use-compress-program=unzstd -xf "$assets_archive" -C "$assets_root"
  source="$assets_root/assets/goldberg"
  if [ ! -s "$source/x86/steam_api.dll" ] || [ ! -s "$source/x64/steam_api64.dll" ]; then
    echo "Goldberg payload is missing from metalsharp-assets.tar.zst" >&2
    rm -rf "$tmp"
    exit 1
  fi

  (
    cd "$source"
    tar -cf "$tmp/goldberg.tar" .
  )
  zstd -q -19 -T0 -f "$tmp/goldberg.tar" -o "$goldberg_archive"
  chmod 0644 "$goldberg_archive"
  rm -rf "$tmp"
  echo "created Goldberg bundle: $goldberg_archive"
}

while IFS=$'\t' read -r asset _root _platforms _notes; do
  case "$asset" in
    ""|\#*) continue ;;
  esac
  if [ "$SKIP_DEVELOPER_SDK" = "1" ] && [ "$asset" = "metalsharp-d3d12-developer-sdk.tar.zst" ]; then
    echo "SKIP bundle: $asset (will be generated by CI)"
    continue
  fi
  download_asset "$asset" "$BUNDLE_DIR/$asset"
done < "$MANIFEST"

if [ "$REPAIR_BUNDLES" = "1" ]; then
  if [ "$REPAIR_M12" = "1" ]; then
    repair_graphics_m12_bundle
  else
    echo "M12 dll repair disabled (METALSHARP_REPAIR_M12!=1); preserving canonical dxmt-m12 lane"
  fi
  repair_assets_fnalibs_bundle

  "$PROJECT_ROOT/tools/dmg/repair-runtime-bundle.py" \
    --archive "$BUNDLE_DIR/metalsharp-runtime.tar.zst" \
    --host-dir "$PROJECT_ROOT/app/native/host" \
    --backend "$PROJECT_ROOT/app/src-rust/target/release/metalsharp-backend"
else
  echo "bundle repair disabled; using verified release bundles as downloaded"
fi

create_goldberg_bundle

VERIFY_ARGS=(--bundle-dir "$BUNDLE_DIR" --require mac)
if [ "$SKIP_DEVELOPER_SDK" = "1" ]; then
  while IFS=$'\t' read -r asset _root _platforms _notes; do
    case "$asset" in
      ""|\#*|metalsharp-d3d12-developer-sdk.tar.zst) continue ;;
    esac
    VERIFY_ARGS+=("$asset")
  done < "$MANIFEST"
fi
"$PROJECT_ROOT/tools/bundles/verify-bundles.sh" "${VERIFY_ARGS[@]}"

rm -f "$OUT_DIR"/metalsharp-*.tar.zst
while IFS=$'\t' read -r asset _root _platforms _notes; do
  case "$asset" in
    ""|\#*) continue ;;
  esac
  if [ "$SKIP_DEVELOPER_SDK" = "1" ] && [ "$asset" = "metalsharp-d3d12-developer-sdk.tar.zst" ]; then
    continue
  fi
  cp "$BUNDLE_DIR/$asset" "$OUT_DIR/$asset"
done < "$MANIFEST"

cp "$BUNDLE_DIR/goldberg.tar.zst" "$OUT_DIR/goldberg.tar.zst"

{
  printf 'asset\troot\tsha256\tsize\tnotes\n'
  while IFS=$'\t' read -r asset root _platforms notes; do
    case "$asset" in
      ""|\#*) continue ;;
    esac
    if [ "$SKIP_DEVELOPER_SDK" = "1" ] && [ "$asset" = "metalsharp-d3d12-developer-sdk.tar.zst" ]; then
      continue
    fi
    archive="$BUNDLE_DIR/$asset"
    hash="$(shasum -a 256 "$archive" | awk '{print $1}')"
    size="$(wc -c < "$archive" | tr -d ' ')"
    printf '%s\t%s\t%s\t%s\t%s\n' "$asset" "$root" "$hash" "$size" "$notes"
  done < "$MANIFEST"
} > "$OUT_DIR/metalsharp-bundle-manifest.tsv"
	echo "goldberg.tar.zst	goldberg	$(shasum -a 256 "$BUNDLE_DIR/goldberg.tar.zst" | awk '{print $1}')	$(wc -c < "$BUNDLE_DIR/goldberg.tar.zst" | tr -d ' ')	generated Goldberg-only bootstrap bundle" >> "$OUT_DIR/metalsharp-bundle-manifest.tsv"

echo ""
echo "=== Split Bundle Summary ==="
ls -lh "$BUNDLE_DIR"/metalsharp-*.tar.zst "$BUNDLE_DIR/goldberg.tar.zst"
