#!/usr/bin/env python3
"""Compare the C backend with the Rust reference.

Semantic mode (the default) masks values that are generated by the host or by
an individual backend process.  --raw keeps every value so it remains useful
for diagnosing real regressions.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import signal
import subprocess
import tempfile
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
RUST_SOURCE = ROOT / "app/src-rust/src/main.rs"
DEFAULT_C = ROOT / "app/src-c/build/metalsharp-backend"
DEFAULT_RUST = Path("/tmp/metalsharp-rust-reference/release/metalsharp-backend")
EXCLUDED = (
    "/setup/install-all",
    "/update/",
    "/kernel-translation/ipc/",
    "/sharp-library/gog/initialize-prefix",
)

DYNAMIC_KEYS = {
    "pid", "own_pid", "watch_pid", "protected_pid", "parent_pid", "backend_pid",
    "created_at", "updated_at", "installed_at", "activated_at", "last_heartbeat",
    "timestamp", "generated_at_unix", "at", "launch_id", "request_id", "last_event",
    "registered_at", "last_fired", "protected_at", "last_activity", "last_crash",
    "page_address", "pageaddress", "base_address", "baseaddress", "trampoline_address",
    "trampolineaddress", "port", "ipc_port", "ipcport", "listen_port", "listenport",
    "ports", "fds", "merged", "backendpid",
}


def route_list() -> list[tuple[str, str]]:
    source = RUST_SOURCE.read_text()
    routes = re.findall(r'\(HttpMethod::(Get|Post),\s*"([^"\\]+)"\)', source)
    result = []
    for route in routes:
        if route not in result and not any(token in route[1] for token in EXCLUDED):
            result.append(route)
    return result


def start(binary: Path, port: int) -> tuple[subprocess.Popen[bytes], str, str]:
    metalsharp_home = tempfile.mkdtemp(prefix="metalsharp-parity-")
    home = tempfile.mkdtemp(prefix="metalsharp-user-")
    env = os.environ.copy()
    env.update(METALSHARP_HOME=metalsharp_home, HOME=home, METALSHARP_PORT=str(port))
    process = subprocess.Popen(
        [str(binary)], env=env, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL
    )
    for _ in range(150):
        try:
            status = subprocess.run(
                ["curl", "-sf", f"http://127.0.0.1:{port}/status"],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                check=False,
            )
            if status.returncode == 0:
                return process, metalsharp_home, home
        except OSError:
            pass
        time.sleep(0.03)
    process.kill()
    raise RuntimeError(f"backend did not start on port {port}: {binary}")


def request(port: int, method: str, path: str) -> tuple[str, object]:
    command = ["curl", "-sS", "--max-time", "5", "-X", method.upper(), "-w", "\nSTATUS:%{http_code}"]
    if method == "Post":
        command += ["-H", "Content-Type: application/json", "-d", "{}"]
    command.append(f"http://127.0.0.1:{port}{path}")
    raw = subprocess.check_output(command, stderr=subprocess.DEVNULL, text=True)
    body, _, status = raw.rpartition("\nSTATUS:")
    try:
        return status, json.loads(body)
    except json.JSONDecodeError:
        return status, ("raw", body[:500])


def canonical(value: object, route: str, roots: tuple[str, str], raw: bool) -> object:
    if raw:
        return value
    if isinstance(value, dict):
        result = {}
        for key, child in value.items():
            normalized_key = key.lower().replace("-", "_")
            if normalized_key in DYNAMIC_KEYS or "address" in normalized_key:
                result[key] = "<dynamic>"
            elif route == "/setup/device-name" and key == "name":
                result[key] = "<dynamic>"
            else:
                result[key] = canonical(child, route, roots, raw)
        return result
    if isinstance(value, list):
        return [canonical(child, route, roots, raw) for child in value]
    if isinstance(value, str):
        result = value
        for root in roots:
            result = result.replace(root, "<temporary-root>")
        result = re.sub(r"/var/folders/[^/]+/[^/]+/T/tmp[^/ ]*", "<temporary-path>", result)
        result = re.sub(r"/tmp/[^/ ]+", "<temporary-path>", result)
        result = re.sub(r"issue-[^/ ]+\.log", "issue-<dynamic>.log", result)
        result = re.sub(r"\[\d{4}-\d\d-\d\d \d\d:\d\d:\d\d [A-Z]+\]", "[TIME]", result)
        result = re.sub(r"(?:127\.0\.0\.1|localhost):\d+", "<host>:<port>", result)
        result = re.sub(r"\b(?:own pid|backend pid|process|PID|pid)\s*[:=]?\s*\d+\b", "<process>", result)
        result = re.sub(r"0x[0-9a-fA-F]{8,}", "<address>", result)
        return result
    return value


def differences(left: object, right: object, path: str = "") -> list[tuple[str, str, object, object]]:
    if type(left) is not type(right):
        return [(path, "type", left, right)]
    if isinstance(left, dict):
        result = []
        for key in sorted(set(left) | set(right)):
            child_path = f"{path}/{key}"
            if key not in left or key not in right:
                result.append((child_path, "missing", left.get(key), right.get(key)))
            else:
                result.extend(differences(left[key], right[key], child_path))
        return result
    if isinstance(left, list):
        if len(left) != len(right):
            return [(path, "length", len(left), len(right))]
        result = []
        for index, (a, b) in enumerate(zip(left, right)):
            result.extend(differences(a, b, f"{path}/{index}"))
        return result
    return [] if left == right else [(path, "value", left, right)]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--c", type=Path, default=Path(os.environ.get("METALSHARP_C", DEFAULT_C)))
    parser.add_argument("--rust", type=Path, default=Path(os.environ.get("METALSHARP_RUST", DEFAULT_RUST)))
    parser.add_argument("--raw", action="store_true", help="Do not normalize generated values")
    parser.add_argument("--c-port", type=int, default=19760)
    parser.add_argument("--rust-port", type=int, default=19761)
    args = parser.parse_args()
    if not args.c.is_file() or not args.rust.is_file():
        parser.error(f"both backends must exist: {args.c}, {args.rust}")

    left_process = right_process = None
    roots: list[tuple[str, str]] = []
    try:
        left_process, left_home, left_user = start(args.c, args.c_port)
        right_process, right_home, right_user = start(args.rust, args.rust_port)
        roots = [(left_home, right_home), (left_user, right_user)]
        flat_roots = (left_home, left_user, right_home, right_user)
        route_mismatches = []
        for method, path in route_list():
            try:
                left = request(args.c_port, method, path)
                right = request(args.rust_port, method, path)
            except (OSError, subprocess.CalledProcessError) as error:
                route_mismatches.append((method, path, [("request", "error", str(error), "")]))
                continue
            if left[0] != right[0]:
                route_mismatches.append((method, path, [("status", "value", left[0], right[0])]))
                continue
            left_body = canonical(left[1], path, flat_roots, args.raw)
            right_body = canonical(right[1], path, flat_roots, args.raw)
            mismatch = differences(left_body, right_body)
            if mismatch:
                route_mismatches.append((method, path, mismatch))
        mode = "raw" if args.raw else "semantic"
        print(f"routes={len(route_list())} mode={mode} mismatched_routes={len(route_mismatches)}")
        for method, path, mismatch in route_mismatches:
            print(f"{method} {path}: {mismatch[:8]}")
        return 1 if route_mismatches else 0
    finally:
        for process in (left_process, right_process):
            if process is not None:
                process.send_signal(signal.SIGTERM)
        for process in (left_process, right_process):
            if process is not None:
                try:
                    process.wait(timeout=2)
                except subprocess.TimeoutExpired:
                    process.kill()
        cleanup_roots = [root for pair in roots for root in pair]
        for root in cleanup_roots:
            shutil.rmtree(root, ignore_errors=True)


if __name__ == "__main__":
    raise SystemExit(main())
